
package Interfaces;

import java.awt.Font;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;







public class FrmBlocodeNotas extends javax.swing.JInternalFrame {

String filename = "";


    public FrmBlocodeNotas() {
        initComponents();
           initComponents();
        // define fonte para o texto
        
        this.jTextArea.setFont(new Font(Font.SANS_SERIF,Font.PLAIN,18));
        
        // define quebra linhas automatica 
        this.jTextArea.setLineWrap(true );
        // definir linha de quebra de palavras
        this.jTextArea.setWrapStyleWord(true);

    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


        setIconifiable(true);
        setMaximizable(true);
        setClosable(true);
        setResizable(true);

        jFileChooser = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuAbrir = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuNovo = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuSalvar = new javax.swing.JRadioButtonMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuSair = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuCopiar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuRecortar = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuColar = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuSobre = new javax.swing.JMenuItem();

        jTextArea.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea.setColumns(20);
        jTextArea.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea.setRows(5);
        jTextArea.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTextArea);

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 51));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setAlignmentY(0.3F);
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenu1.setText("Arquivo");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuAbrir.setSelected(true);
        jMenuAbrir.setText("Abrir");
        jMenuAbrir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuAbrir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jMenuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAbrir);
        jMenu1.add(jSeparator1);

        jMenuNovo.setText("Novo");
        jMenuNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNovoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuNovo);
        jMenu1.add(jSeparator3);

        jMenuSalvar.setSelected(true);
        jMenuSalvar.setText("Salvar");
        jMenuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalvarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSalvar);
        jMenu1.add(jSeparator6);

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSair);

        jMenuBar1.add(jMenu1);

        jMenuEditar.setText("Editar");
        jMenuEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jMenuCopiar.setText("Copiar");
        jMenuCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCopiarActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuCopiar);
        jMenuEditar.add(jSeparator2);

        jMenuRecortar.setText("Recortar");
        jMenuRecortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRecortarActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuRecortar);
        jMenuEditar.add(jSeparator4);

        jMenuColar.setText("Colar");
        jMenuColar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuColarActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuColar);

        jMenuBar1.add(jMenuEditar);

        jMenuAjuda.setText("Ajuda");
        jMenuAjuda.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jMenuSobre.setText("Sobre");
        jMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuSobre);

        jMenuBar1.add(jMenuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAbrirActionPerformed
 // exibi caixa de dialogo para abrir arquivo 
       
int selecao = jFileChooser.showOpenDialog(jMenuAbrir);

        if (selecao == 0) {

            try {
                BufferedReader ler = null;
                File arquivo = jFileChooser.getSelectedFile();
                ler = new BufferedReader(new FileReader(arquivo));

                String linha = ler.readLine();
                while (linha != null) {
                    jTextArea.append(linha);
                    jTextArea.append(System.getProperty("line.separador"));
                    linha = ler.readLine();
                }
                ler.close();

            } catch (FileNotFoundException ex) {

            } catch (IOException ex) {
            }

        }
    }//GEN-LAST:event_jMenuAbrirActionPerformed

    private void jMenuNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNovoActionPerformed

        jTextArea.setText("");
    }//GEN-LAST:event_jMenuNovoActionPerformed

    private void jMenuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalvarActionPerformed

        //invoca metodo save
        save();
         jTextArea.setText("");
        
        
    }//GEN-LAST:event_jMenuSalvarActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed

        if ("".equals(jTextArea.getText())) {

            System.exit(0);

            // texto presente na area de trabalho: opção salvar ou
        } else {

            String OLA = " Esta certo disso ? Posso continuar ? ";

            int confirmar = JOptionPane.showConfirmDialog(null, OLA);
            if (confirmar == JOptionPane.YES_OPTION);
            {
                if (filename.equals("")) {
                    //saveAs();

                } else {
                    save();

                }
            }

            if  (confirmar == JOptionPane.NO_OPTION) {
                System.exit(0);
            }
        }
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCopiarActionPerformed
        // TODO add your handling code here:

        jTextArea.copy();

    }//GEN-LAST:event_jMenuCopiarActionPerformed

    private void jMenuRecortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRecortarActionPerformed

        jTextArea.cut();

    }//GEN-LAST:event_jMenuRecortarActionPerformed

    private void jMenuColarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuColarActionPerformed
        jTextArea.paste();
    }//GEN-LAST:event_jMenuColarActionPerformed

    private void jMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSobreActionPerformed
        //exibir umacaixa de dialogo

        String msg = "Desenvolvido por" + "\nFundação Mello ";
        JOptionPane.showMessageDialog(null, msg);

    }//GEN-LAST:event_jMenuSobreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JRadioButtonMenuItem jMenuAbrir;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuColar;
    private javax.swing.JMenuItem jMenuCopiar;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenuItem jMenuNovo;
    private javax.swing.JMenuItem jMenuRecortar;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JRadioButtonMenuItem jMenuSalvar;
    private javax.swing.JMenuItem jMenuSobre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables

    
    private void save() {

        // exibir caixa de dialogo
        int selecao = jFileChooser.showSaveDialog(jMenuSalvar);

        if (selecao == 0) {

            try {
                BufferedReader ler = null;
                File arquivo = jFileChooser.getSelectedFile();
                PrintWriter escrever = new PrintWriter(arquivo);
                escrever.print(jTextArea.getText());
                escrever.close();
            } catch (FileNotFoundException ex) {
            }
        }

    }


}
