
package Interfaces;

import java.awt.Color;


public class FrmParImpar extends javax.swing.JInternalFrame {
  public int n1;
    public int n2;
    public FrmParImpar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        
        setIconifiable(true);
        setMaximizable(true);
        setClosable(true);
        setResizable(true);


        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        txtErro = new javax.swing.JTextField();
        btnApagar = new javax.swing.JButton();
        btnImpar = new javax.swing.JButton();
        btnPares = new javax.swing.JButton();
        text2 = new javax.swing.JTextField();
        text1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(0, 0, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Inserir valor incial :");

        textArea.setBackground(new java.awt.Color(255, 255, 255));
        textArea.setColumns(20);
        textArea.setForeground(new java.awt.Color(0, 0, 0));
        textArea.setRows(5);
        textArea.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane1.setViewportView(textArea);

        txtErro.setBackground(new java.awt.Color(255, 255, 255));
        txtErro.setForeground(new java.awt.Color(0, 0, 0));
        txtErro.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        txtErro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtErroActionPerformed(evt);
            }
        });

        btnApagar.setBackground(new java.awt.Color(204, 204, 204));
        btnApagar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnApagar.setForeground(new java.awt.Color(0, 0, 0));
        btnApagar.setText("Novos Valores");
        btnApagar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnApagar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnImpar.setBackground(new java.awt.Color(204, 204, 204));
        btnImpar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnImpar.setForeground(new java.awt.Color(0, 0, 0));
        btnImpar.setText("Numeros Impares");
        btnImpar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnImpar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnImpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImparActionPerformed(evt);
            }
        });

        btnPares.setBackground(new java.awt.Color(204, 204, 204));
        btnPares.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnPares.setForeground(new java.awt.Color(0, 0, 0));
        btnPares.setText("Numeros Pares");
        btnPares.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnPares.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParesActionPerformed(evt);
            }
        });

        text2.setBackground(new java.awt.Color(255, 255, 255));
        text2.setForeground(new java.awt.Color(0, 0, 0));
        text2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 51)));

        text1.setBackground(new java.awt.Color(255, 255, 255));
        text1.setForeground(new java.awt.Color(0, 0, 0));
        text1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 51)));
        text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Inserir valor Final:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnImpar, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(btnPares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtErro, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtErro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPares, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnImpar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        limpar();
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnImparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImparActionPerformed
        if (verificaValor()) {
            textArea.setText("");
            if (n1 > n2) {
                int i;
                for (i = n1; i >= n2; i--) {

                    if (i % 2 != 0) {

                        textArea.append("Numeros Impares " + i + "\n");

                    }

                }
            }

            // calculo de numeros pares
            int i;
            for (i = n1; i <= n2; i++) {

                if (i % 2 != 0) {

                    textArea.append("Numeros Impares " + i + "\n");
                }
                }
            }
    }//GEN-LAST:event_btnImparActionPerformed

    private void btnParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParesActionPerformed

        // conversao de String para Int
        if (verificaValor()) {
            textArea.setText("");
            if (n1 > n2) {

                // calculo de numeros pares
                for (int i = n1; i >= n2; i--) {

                    if (i % 2 == 0) {

                        textArea.append("Numeros pares " + i + "\n");

                    }
                }

            } else {

                // calculo de numeros pares
                for (int i = n1; i <= n2; i++) {

                    if (i % 2 == 0) {

                        textArea.append("Numeros pares " + i + "\n");

                    }
                }

            }

    }//GEN-LAST:event_btnParesActionPerformed
    }
    private void text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text1ActionPerformed

    }//GEN-LAST:event_text1ActionPerformed

    private void txtErroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtErroActionPerformed
   txtErro.setEditable(false);
    }//GEN-LAST:event_txtErroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnImpar;
    private javax.swing.JButton btnPares;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField txtErro;
    // End of variables declaration//GEN-END:variables

 private boolean verificaValor() {

        
        
        try {

            n1 = Integer.parseInt(this.text1.getText());
            n2 = Integer.parseInt(this.text2.getText());
            return true;

        } catch (NumberFormatException e) {

            if (text1.getText().isEmpty() || text1.getText().matches("[a-z]")) {
                txtErro.setForeground(Color.red);
                txtErro.setText("Invalido, digite um valor inicial");
                text1.setText("");
                text1.requestFocus();

            } else if (text2.getText().isEmpty() || text2.getText().matches("[a-z]")) {
                txtErro.setForeground(Color.RED);
                txtErro.setText("Invalido, digite um valor final");
                text2.setText("");
                text2.requestFocus();
            }

        }

        return false;
    }

    void limpar() {

        this.textArea.setText("");
        this.text1.setText("");
        this.text2.setText("");
        this.txtErro.setText("");

    }


}
